### PR TITLE
Fix install on macOS 10.12.4

### PR DESCRIPTION
**Pull request by AlJohri**
### Changes

Summary of changes:
- https://github.com/berkmancenter/mediacloud/pull/138/commits/1ed495bb41590c009cbc6b6748e80a8bb4c8a1f9 change `purge_all.sh` to delete the `mc-venv` virtual environment
- https://github.com/berkmancenter/mediacloud/pull/138/commits/9eedc9d68b82837b11d98182beadba20d5e9cb28 add echo before asking for sudo in `set_postgresql_parameters.sh`
- https://github.com/berkmancenter/mediacloud/pull/138/commits/0ac4ccf6bd457941a57dcef93f3480fcb9af8ef6 create a variable with the major python version, "3.5", that can later be more easily updated to 3.6
- https://github.com/berkmancenter/mediacloud/pull/138/commits/5898e8460cf0cacc1bdf68213c6bc265fe0e74f9 allow perlbrew lib create to fail if the library already exists
- https://github.com/berkmancenter/mediacloud/pull/138/commits/6a8d5c12a83e66b3937d5ffdb5ed9e19fa891c42 add https package to global cpanm for installation of github https modules which fail otherwise
- https://github.com/berkmancenter/mediacloud/pull/138/commits/32f20b56a2a1a096218c46ccb235e15893dcbbd0 fix error check for creratedb and createuser for postgres
- https://github.com/berkmancenter/mediacloud/pull/138/commits/2d480d426b04aa1cbe83abc7c2eab9761e44c049 add `root` postgres user because it doesn't exist on homebrew installed postgres. also use `brew services` instead of `launchctl`
- https://github.com/berkmancenter/mediacloud/pull/138/commits/ea99c71770dfd8a2289986c98710595f0441eec1 use homebrew perl as system perl on macOS. makes sudo unnecessary and also doesn't require perlbrew to compile perl from scratch anymore. force install graphviz due to some failing tests. don't hardcode vagrant path to test for vagrant
- https://github.com/berkmancenter/mediacloud/pull/138/commits/4cc413fa42e6ee45cbd3c56bad35993afb792d50 the cpanfile.snapshot changed by itself

Each commit has more details in the description.

### Testing

Tested locally on macOS 10.12.4:

```
$ ./install.sh
...
Media Cloud install succeeded!!!!
See doc/ for more information on using Media Cloud
Run ./script/start_mediacloud_server.sh to start the Media Cloud server
(Log in with email address 'jdoe@mediacloud.org' and password 'mediacloud')
```

Full Log: https://gist.github.com/AlJohri/ee219e8bf0f7bbce2845a1c2888660c1

I'm having issues with Inline::Python and virtualenv which I'll work out with @pypt when he has some time. Otherwise, I've worked around the issue and everything is running properly.

```
$ ./script/start_mediacloud_server.sh
Running plackup on Carton on PID 77264 and arguments:
HTTP::Server::PSGI: Accepting connections at http://0:5000/
^C2017-04-06 16:44:54,474 IO.Socket: ^c exiting  ...
```

cc @pypt for review

### CODE REVIEW

**Comment by pypt** [comment]
Thanks Al, great PR!

**Comment by pypt** [comment]
I've only reversed the OS X build on Travis for now, please see 89fbd8e commit message for motivation.

In short, maintaining stable OS X build would be useful, but someone has to do all the huffing and puffing with Travis first, then merge it into `master`.

Running a knowingly failing Travis build over and over again doesn't accomplish much and most likely makes us wait extra for available resources on Travis.

**Comment by esirK** [comment]
the `./install.sh` doesn't work on `Mac Os 10.15.4 `  this is due to https://github.com/berkmancenter/mediacloud/blob/master/install.sh#L15 `apt-get` which is not available on mac os. Was this a change made later on or why does your `./install.sh` work? Thanks.

**Comment by pypt** [comment]
You can replace `apt-get` with a Homebrew command to install both Python and Pip - I think this should be enough to be able to run in.

**Pull request merged**
